"""ProgramExercise

Revision ID: 02f94325189d
Revises: c73f85d3bd3b
Create Date: 2025-09-20 01:02:02.699589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f94325189d'
down_revision: Union[str, Sequence[str], None] = 'c73f85d3bd3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_photos_id'), 'client_photos', ['id'], unique=False)
    op.create_table('program_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('block_order', sa.Integer(), nullable=True),
    sa.Column('exercise_order', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_exercises_id'), 'program_exercises', ['id'], unique=False)
    op.drop_table('program_exercise')
    op.drop_column('clients', 'photo_before')
    op.drop_column('clients', 'photo_after')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('photo_after', sa.VARCHAR(), nullable=True))
    op.add_column('clients', sa.Column('photo_before', sa.VARCHAR(), nullable=True))
    op.create_table('program_exercise',
    sa.Column('program_id', sa.INTEGER(), nullable=True),
    sa.Column('exercise_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], )
    )
    op.drop_index(op.f('ix_program_exercises_id'), table_name='program_exercises')
    op.drop_table('program_exercises')
    op.drop_index(op.f('ix_client_photos_id'), table_name='client_photos')
    op.drop_table('client_photos')
    # ### end Alembic commands ###
