"""client updating 2

Revision ID: 2d5adc9655fb
Revises: 9146eade671c
Create Date: 2025-10-19 12:17:35.412394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d5adc9655fb'
down_revision: Union[str, Sequence[str], None] = '9146eade671c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'research_results')
    op.drop_column('clients', 'massage_recommendations')
    op.drop_column('clients', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('age', sa.INTEGER(), nullable=True))
    op.add_column('clients', sa.Column('massage_recommendations', sa.TEXT(), nullable=True))
    op.add_column('clients', sa.Column('research_results', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
