"""ProgramExercise_1

Revision ID: 6f8fadcf1926
Revises: 02f94325189d
Create Date: 2025-09-20 01:44:21.811338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f8fadcf1926'
down_revision: Union[str, Sequence[str], None] = '02f94325189d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('repeats', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_exercise_id'), 'program_exercise', ['id'], unique=False)
    op.drop_index(op.f('ix_program_exercises_id'), table_name='program_exercises')
    op.drop_table('program_exercises')
    op.add_column('client_photos', sa.Column('photo_url', sa.String(), nullable=False))
    op.drop_column('client_photos', 'file_path')
    op.drop_column('clients', 'phone')
    op.drop_column('clients', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('telegram_id', sa.VARCHAR(), nullable=True))
    op.add_column('clients', sa.Column('phone', sa.VARCHAR(), nullable=True))
    op.add_column('client_photos', sa.Column('file_path', sa.VARCHAR(), nullable=False))
    op.drop_column('client_photos', 'photo_url')
    op.create_table('program_exercises',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('program_id', sa.INTEGER(), nullable=True),
    sa.Column('exercise_id', sa.INTEGER(), nullable=True),
    sa.Column('block_order', sa.INTEGER(), nullable=True),
    sa.Column('exercise_order', sa.INTEGER(), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('reps', sa.INTEGER(), nullable=True),
    sa.Column('sets', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.INTEGER(), nullable=True),
    sa.Column('time', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_exercises_id'), 'program_exercises', ['id'], unique=False)
    op.drop_index(op.f('ix_program_exercise_id'), table_name='program_exercise')
    op.drop_table('program_exercise')
    # ### end Alembic commands ###
