"""webhooks

Revision ID: 9146eade671c
Revises: f46156f2f316
Create Date: 2025-10-18 23:44:10.667225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9146eade671c'
down_revision: Union[str, Sequence[str], None] = 'f46156f2f316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'telegram_id')
    op.drop_column('clients', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone', sa.VARCHAR(), nullable=True))
    op.add_column('clients', sa.Column('telegram_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
