"""ProgramExercise_2

Revision ID: a2b890557bb6
Revises: 6f8fadcf1926
Create Date: 2025-09-20 01:45:56.260054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b890557bb6'
down_revision: Union[str, Sequence[str], None] = '6f8fadcf1926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('telegram_id', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'phone')
    op.drop_column('clients', 'telegram_id')
    # ### end Alembic commands ###
