"""client adding age

Revision ID: c6b053da90c3
Revises: 2d5adc9655fb
Create Date: 2025-10-19 12:18:58.579741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b053da90c3'
down_revision: Union[str, Sequence[str], None] = '2d5adc9655fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('clients', 'age')
    # ### end Alembic commands ###
